alias lazyuno="/data/bin/lazysingle uno"
alias lazydos="/data/bin/lazysingle dos"
alias lazytres="/data/bin/lazysingle tres"
alias lazydiez="/data/bin/lazysingle diez"
alias lazyonce="/data/bin/lazysingle once"
alias lazydoce="/data/bin/lazysingle doce"
alias lazytrece="/data/bin/lazysingle trece"