alias lazyuno="/data/linux/bin/lazysingle uno"
alias lazydos="/data/linux/bin/lazysingle dos"
alias lazytres="/data/linux/bin/lazysingle tres"
alias lazydiez="/data/linux/bin/lazysingle diez"
alias lazyonce="/data/linux/bin/lazysingle once"
alias lazydoce="/data/linux/bin/lazysingle doce"
alias lazytrece="/data/linux/bin/lazysingle trece"